# Generated by Django 5.2.17 on 2026-08-13 17:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_item_options_item_image_item_is_available_and_more'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text="Current quantity. A cached running total of this item's movements, rebuildable from them if it is ever doubted.", max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Warn when the quantity reaches this. Held per branch rather than per item, because a kiosk and a depot reorder at different points.', max_digits=12)),
                ('last_counted_at', models.DateTimeField(blank=True, help_text='When someone last physically counted this.', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='catalog.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'inventory_stock_item',
                'ordering': ('item__name',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.DecimalField(decimal_places=3, help_text='Signed change. Negative takes stock away.', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=3, help_text='Quantity immediately after this movement. Stored so history reads without replaying the whole ledger, and so a later disagreement can be traced to the movement that introduced it.', max_digits=12)),
                ('reason', models.CharField(choices=[('PURCHASE', 'Stock received'), ('RETURN', 'Customer return'), ('ADJUSTMENT', 'Manual adjustment'), ('WASTAGE', 'Damaged, expired or lost'), ('COUNT', 'Stock count correction'), ('TRANSFER_IN', 'Transferred in from another branch'), ('TRANSFER_OUT', 'Transferred out to another branch'), ('SALE', 'Sold'), ('REFUND', 'Refunded')], max_length=16)),
                ('note', models.TextField(blank=True, help_text='Why. Required for adjustments, wastage and count corrections.')),
                ('ref_type', models.CharField(blank=True, max_length=32)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Who made the change. Null only for automated corrections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tenant', 'store'], name='inventory_s_tenant__6864b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'item', 'store'), name='unique_stock_per_item_store'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', '-created_at'], name='inventory_s_tenant__f5ad82_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='inventory_s_stock_i_d0fe83_idx'),
        ),
        # Tenant isolation is enforced by the database, not only by
        # application code. The coverage test fails the build if either of
        # these tables ships without a policy. See apps/core/db/rls.py.
        *enable_rls_for("inventory_stock_item", "inventory_stock_movement"),
    ]
