"""
Shifts, and the cash drawer a shift is accountable for.

A shift is one cashier, one drawer, one till, for one stretch of time. Closing
one is the moment a person counts money and puts their name to a figure, which
makes it the most sensitive record in the system after the sales themselves.

Four decisions shape everything here.

**The count is blind.** A cashier declares what is in the drawer before the
system tells them what it expected. Showing the expected figure first turns the
count into typing a number back, and the control becomes theatre - which is
worse than no control, because it looks like one.

**M-Pesa never enters the expected-cash figure.** A drawer holds cash. Folding
mobile money into it is how a shop's drawer reads twenty thousand short every
day and nobody trusts the reconciliation again.

**Closing figures are frozen.** Once a shift is closed, its expected total and
its variance never change. An offline sale that arrives days later is recorded
against the shift as a ``LATE_ATTRIBUTION`` discrepancy rather than quietly
rewriting what somebody signed off. This is the same principle as no
PAID-to-VOID and append-only ledgers: a close-time figure records what was true
when a person was accountable for it, not a running total that drifts as more
data arrives. Recomputing would mean two different correct answers exist for
"what was this shift's variance", depending on when you ask.

**A payment names its shift explicitly.** Not a time-window query. A sale rung
up during a shift but synced after it closed would fall outside a server-time
window and vanish from the reconciliation entirely - and that is precisely the
sale a shop most needs accounted for.
"""

from __future__ import annotations

from django.db import models

from apps.core.models import TenantOwnedModel, TimeStampedModel, UUIDModel


class ShiftState(models.TextChoices):
    """Two states, and no way back.

    There is no reopening. A correction after the fact is a new cash movement
    or an adjustment recorded against the closed shift, never an edit - the
    same append-only discipline the payment and refund ledgers follow, and for
    the same reason: an editable record of who counted what is not a record.
    """

    OPEN = "OPEN", "Open"
    CLOSED = "CLOSED", "Closed"


class Shift(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """One cashier's stretch of responsibility for one drawer."""

    client_uuid = models.UUIDField(
        null=True,
        blank=True,
        help_text=(
            "Generated by the till when the shift is opened, so a shift opened "
            "with no connection can be replayed exactly once. Unique per "
            "business, the same way a sale's is."
        ),
    )

    store = models.ForeignKey(
        "stores.Store", on_delete=models.PROTECT, related_name="shifts"
    )
    device = models.ForeignKey(
        "accounts.Device",
        on_delete=models.SET_NULL,
        related_name="shifts",
        null=True,
        blank=True,
        help_text="Which till. A drawer belongs to a counter, not to a person.",
    )
    cashier = models.ForeignKey(
        "accounts.User",
        on_delete=models.PROTECT,
        related_name="shifts",
        help_text="Who is accountable for this drawer. PROTECT, so the name survives.",
    )

    state = models.CharField(
        max_length=10, choices=ShiftState.choices, default=ShiftState.OPEN
    )

    opened_at = models.DateTimeField()
    closed_at = models.DateTimeField(null=True, blank=True)

    opening_float_cents = models.BigIntegerField(
        default=0,
        help_text="Counted cash placed in the drawer at the start, to give change from.",
    )

    # ---- Frozen at close, never recomputed ------------------------------

    declared_closing_cents = models.BigIntegerField(
        null=True,
        blank=True,
        help_text="What the cashier counted. Entered before they are shown the expectation.",
    )
    expected_closing_cents = models.BigIntegerField(
        null=True,
        blank=True,
        help_text=(
            "What the drawer should have held, computed once at close and "
            "never again. A later-arriving sale raises a discrepancy rather "
            "than changing this."
        ),
    )
    variance_cents = models.BigIntegerField(
        null=True,
        blank=True,
        help_text=(
            "Declared minus expected. Negative is short, positive is over. "
            "Never blocks a close - the count is a fact to record, and a shop "
            "that cannot close its till stops trading."
        ),
    )

    closed_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        related_name="closed_shifts",
        null=True,
        blank=True,
        help_text=(
            "Usually the cashier. A manager closing somebody else's drawer - "
            "because they went home - is recorded here and audited as such."
        ),
    )

    opening_note = models.TextField(blank=True)
    closing_note = models.TextField(blank=True)

    class Meta:
        db_table = "shifts_shift"
        ordering = ("-opened_at",)
        constraints = [
            models.UniqueConstraint(
                fields=["tenant", "client_uuid"],
                condition=models.Q(client_uuid__isnull=False),
                name="unique_shift_client_uuid_per_tenant",
            ),
            # One open drawer per cashier at a time. Two would make "which
            # drawer did this sale go into" unanswerable, and the answer is the
            # entire point of the record.
            models.UniqueConstraint(
                fields=["tenant", "cashier"],
                condition=models.Q(state="OPEN"),
                name="one_open_shift_per_cashier",
            ),
            models.CheckConstraint(
                condition=models.Q(opening_float_cents__gte=0),
                name="shift_float_not_negative",
            ),
        ]
        indexes = [
            models.Index(fields=["tenant", "state", "-opened_at"]),
            models.Index(fields=["tenant", "store", "-opened_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.cashier_id} at {self.store_id} from {self.opened_at:%Y-%m-%d %H:%M}"

    @property
    def is_open(self) -> bool:
        return self.state == ShiftState.OPEN

    @property
    def is_short(self) -> bool:
        """Less cash than expected. The direction a shop cares about most."""
        return self.variance_cents is not None and self.variance_cents < 0

    @property
    def is_over(self) -> bool:
        """More cash than expected. Not good news - it means something was
        mis-rung, and the customer who was overcharged is the one who lost."""
        return self.variance_cents is not None and self.variance_cents > 0


class CashMovementKind(models.TextChoices):
    """Cash crossing the drawer for a reason that is not a sale."""

    PAID_IN = "PAID_IN", "Cash put in"
    PAID_OUT = "PAID_OUT", "Cash taken out"
    #: Excess moved to the safe mid-shift, so a busy counter is not holding a
    #: day's takings. Signed like a PAID_OUT but named apart, because a shop
    #: reading its own history needs to tell a banking run from a purchase.
    DROP = "DROP", "Moved to the safe"


class CashMovement(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """Money into or out of the drawer that no sale accounts for.

    Append-only, like every other money ledger here. A movement recorded in
    error is corrected by an opposite movement, never by editing the original -
    otherwise the drawer's history is only as good as the last person to touch
    it.
    """

    shift = models.ForeignKey(Shift, on_delete=models.PROTECT, related_name="movements")
    kind = models.CharField(max_length=10, choices=CashMovementKind.choices)
    amount_cents = models.BigIntegerField(
        help_text="Always positive. The kind decides the direction."
    )
    reason = models.TextField(
        help_text="Required. 'Cash out' with no reason is indistinguishable from theft."
    )
    user = models.ForeignKey(
        "accounts.User",
        on_delete=models.PROTECT,
        related_name="cash_movements",
    )

    class Meta:
        db_table = "shifts_cash_movement"
        ordering = ("created_at",)
        constraints = [
            models.CheckConstraint(
                condition=models.Q(amount_cents__gt=0),
                name="cash_movement_is_positive",
            ),
        ]
        indexes = [models.Index(fields=["tenant", "shift"])]

    def __str__(self) -> str:
        return f"{self.kind} {self.amount_cents}"

    @property
    def signed_cents(self) -> int:
        """What this does to the drawer."""
        return self.amount_cents if self.kind == CashMovementKind.PAID_IN else -self.amount_cents


class DrawerCount(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """One denomination, and how many of it were counted.

    Optional, and worth having. A shift that is nine hundred short with a
    breakdown showing nine hundred-shilling notes fewer than expected is a
    miscount somebody can find; the same variance with only a total is a
    mystery that gets written off.
    """

    shift = models.ForeignKey(Shift, on_delete=models.PROTECT, related_name="counts")
    denomination_cents = models.IntegerField(
        help_text="The note or coin, in cents. 100000 is a thousand-shilling note."
    )
    quantity = models.PositiveIntegerField()

    class Meta:
        db_table = "shifts_drawer_count"
        ordering = ("-denomination_cents",)
        constraints = [
            models.UniqueConstraint(
                fields=["shift", "denomination_cents"],
                name="one_row_per_denomination_per_shift",
            ),
            models.CheckConstraint(
                condition=models.Q(denomination_cents__gt=0),
                name="denomination_is_positive",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.quantity} x {self.denomination_cents}"

    @property
    def total_cents(self) -> int:
        return self.denomination_cents * self.quantity


class ShiftDiscrepancy(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """Something about a drawer that a person needs to look at.

    Separate from ``SaleDiscrepancy`` because these are not about a sale. A
    variance belongs to a count, and a late attribution belongs to a shift that
    is already closed.
    """

    class Kind(models.TextChoices):
        VARIANCE = "VARIANCE", "The count did not match the expectation"
        LATE_ATTRIBUTION = (
            "LATE_ATTRIBUTION",
            "A sale arrived after its shift had been closed",
        )
        FORCED_CLOSE = "FORCED_CLOSE", "A manager closed somebody else's drawer"

    #: Always set. Joining a shift's frozen figures to whatever arrived after
    #: it closed is then a query rather than an investigation - which is what
    #: makes the frozen-figures decision liveable when reporting arrives.
    shift = models.ForeignKey(
        Shift, on_delete=models.PROTECT, related_name="discrepancies"
    )
    kind = models.CharField(max_length=20, choices=Kind.choices)
    detail = models.TextField()
    context = models.JSONField(default=dict, blank=True)

    resolved_at = models.DateTimeField(null=True, blank=True)
    resolved_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        related_name="resolved_shift_discrepancies",
        null=True,
        blank=True,
    )
    resolution_note = models.TextField(blank=True)

    class Meta:
        db_table = "shifts_discrepancy"
        ordering = ("-created_at",)
        indexes = [
            models.Index(fields=["tenant", "resolved_at", "-created_at"]),
            models.Index(fields=["tenant", "shift"]),
        ]

    def __str__(self) -> str:
        return f"{self.kind} on {self.shift_id}"

    @property
    def is_open(self) -> bool:
        return self.resolved_at is None
