"""
The wire shapes for shifts.

One thing here is a control rather than a convenience: **no serializer that a
cashier can reach before closing returns the expected figure.** It is available
only on the response to the close itself, once the count has been committed.
Putting it on the open-shift representation would make the blind count a
courtesy the interface extends rather than something the API enforces.
"""

from __future__ import annotations

from rest_framework import serializers

from apps.shifts.models import CashMovement, CashMovementKind, Shift, ShiftDiscrepancy


class OpenShiftSerializer(serializers.Serializer):
    """Starting a drawer."""

    opening_float_cents = serializers.IntegerField(
        min_value=0,
        help_text="Counted cash placed in the drawer to give change from.",
    )
    store_id = serializers.UUIDField(required=False, allow_null=True)
    device_id = serializers.UUIDField(required=False, allow_null=True)
    client_uuid = serializers.UUIDField(
        required=False,
        allow_null=True,
        help_text=(
            "Generated by the till, so a shift opened with no connection is "
            "replayed exactly once."
        ),
    )
    note = serializers.CharField(required=False, allow_blank=True)


class CloseShiftSerializer(serializers.Serializer):
    """Counting the drawer.

    The request carries the count and nothing about the expectation, because
    the caller has not been told it. That is the point.
    """

    declared_closing_cents = serializers.IntegerField(
        min_value=0,
        help_text="What was actually counted in the drawer.",
    )
    denominations = serializers.DictField(
        child=serializers.IntegerField(min_value=0),
        required=False,
        help_text=(
            "Optional breakdown, keyed by denomination in cents. A variance "
            "with a breakdown is a miscount somebody can find; the same "
            "variance with only a total is a mystery that gets written off. "
            "Must sum to the declared total."
        ),
    )
    note = serializers.CharField(required=False, allow_blank=True)

    def validate_denominations(self, value):
        cleaned = {}
        for raw_denomination, quantity in value.items():
            try:
                denomination = int(raw_denomination)
            except (TypeError, ValueError):
                raise serializers.ValidationError(
                    f"'{raw_denomination}' is not a denomination."
                ) from None
            if denomination <= 0:
                raise serializers.ValidationError("A denomination must be positive.")
            if quantity:
                cleaned[denomination] = quantity
        return cleaned


class CashMovementSerializer(serializers.Serializer):
    """Money in or out of the drawer for something that is not a sale."""

    kind = serializers.ChoiceField(choices=CashMovementKind.choices)
    amount_cents = serializers.IntegerField(min_value=1)
    reason = serializers.CharField(
        max_length=500,
        help_text="Required. 'Cash out' with no reason is indistinguishable from theft.",
    )


class CashMovementReadSerializer(serializers.ModelSerializer):
    recorded_by = serializers.CharField(source="user.username", read_only=True)

    class Meta:
        model = CashMovement
        fields = ("id", "kind", "amount_cents", "reason", "recorded_by", "created_at")
        read_only_fields = fields


class ShiftDiscrepancySerializer(serializers.ModelSerializer):
    is_open = serializers.BooleanField(read_only=True)

    class Meta:
        model = ShiftDiscrepancy
        fields = ("id", "kind", "detail", "context", "is_open", "created_at")
        read_only_fields = fields


class ShiftSerializer(serializers.ModelSerializer):
    """A shift as the till sees it.

    Carries the closing figures, which are null while it is open - so this same
    serializer is safe to return from every endpoint, and there is no variant
    that could accidentally leak an expectation to a drawer still being
    counted.
    """

    cashier_name = serializers.CharField(source="cashier.full_name", read_only=True)
    cashier_username = serializers.CharField(source="cashier.username", read_only=True)
    store_code = serializers.CharField(source="store.code", read_only=True)
    closed_by_username = serializers.CharField(
        source="closed_by.username", read_only=True, default=None
    )
    movements = CashMovementReadSerializer(many=True, read_only=True)
    discrepancies = ShiftDiscrepancySerializer(many=True, read_only=True)

    class Meta:
        model = Shift
        fields = (
            "id",
            "client_uuid",
            "state",
            "store",
            "store_code",
            "device",
            "cashier",
            "cashier_name",
            "cashier_username",
            "opened_at",
            "closed_at",
            "opening_float_cents",
            "declared_closing_cents",
            "expected_closing_cents",
            "variance_cents",
            "closed_by",
            "closed_by_username",
            "opening_note",
            "closing_note",
            "movements",
            "discrepancies",
        )
        read_only_fields = fields
