/// The till's pricing must agree with the server's, to the cent.
///
/// `lib/data/cart/pricing.dart` is a second implementation of
/// `backend/apps/sales/pricing.py`, written because a cashier cannot be told
/// "no total until the network comes back". Two implementations of the same
/// arithmetic drift unless something forces them together, and the cost of
/// drift here is a receipt that disagrees with what the shop is owed.
///
/// So the fixture is generated by the **server's** pricer
/// (`backend/gen_pricing_fixture.py`) across a spread of awkward carts —
/// fractional quantities, mixed inclusive and exclusive tax on one sale, line
/// and cart discounts together, prices large enough to expose a rounding
/// difference — and this asserts the Dart reproduces every figure exactly.
///
/// If this fails after a change to either file, the two have diverged and the
/// question is which one is right, not which test to update.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:pos_till/data/cart/pricing.dart';

void main() {
  late List<dynamic> cases;

  setUpAll(() {
    final raw = File('test/fixtures/pricing_cases.json').readAsStringSync();
    cases = (jsonDecode(raw) as Map<String, dynamic>)['cases'] as List<dynamic>;
  });

  test('the fixture is actually loaded', () {
    // A fixture that silently failed to load would make every assertion below
    // vacuous, and the suite would pass while proving nothing.
    expect(cases, isNotEmpty);
    expect(cases.length, greaterThanOrEqualTo(100));
  });

  test('every cart prices identically to the server', () {
    var checked = 0;

    for (var index = 0; index < cases.length; index++) {
      final testCase = cases[index] as Map<String, dynamic>;
      final lines = [
        for (final raw in testCase['lines'] as List<dynamic>)
          LineInput(
            itemId: raw['item_id'] as String,
            name: raw['name'] as String,
            unitPriceCents: raw['unit_price_cents'] as int,
            quantityMilli: raw['quantity_milli'] as int,
            taxRateBps: raw['tax_rate_bps'] as int,
            taxIsInclusive: raw['tax_is_inclusive'] as bool,
            discountBps: raw['discount_bps'] as int,
            discountCents: raw['discount_cents'] as int,
          ),
      ];

      final totals = priceCart(
        lines,
        cartDiscountBps: testCase['cart_discount_bps'] as int,
        cartDiscountCents: testCase['cart_discount_cents'] as int,
      );

      final expected = testCase['expected'] as Map<String, dynamic>;
      final where = 'case $index';

      expect(totals.subtotalCents, expected['subtotal_cents'], reason: '$where subtotal');
      expect(totals.discountCents, expected['discount_cents'], reason: '$where discount');
      expect(totals.taxCents, expected['tax_cents'], reason: '$where tax');
      expect(totals.totalCents, expected['total_cents'], reason: '$where total');

      final expectedLines = expected['lines'] as List<dynamic>;
      expect(totals.lines.length, expectedLines.length, reason: '$where line count');

      for (var line = 0; line < expectedLines.length; line++) {
        final want = expectedLines[line] as Map<String, dynamic>;
        final got = totals.lines[line];
        final at = '$where line $line';

        expect(got.grossBeforeDiscountCents, want['gross_before_discount_cents'], reason: '$at gross');
        expect(got.lineDiscountCents, want['line_discount_cents'], reason: '$at line discount');
        expect(got.cartDiscountShareCents, want['cart_discount_share_cents'], reason: '$at share');
        expect(got.netCents, want['net_cents'], reason: '$at net');
        expect(got.taxCents, want['tax_cents'], reason: '$at tax');
        expect(got.grossCents, want['gross_cents'], reason: '$at gross total');
      }
      checked++;
    }

    expect(checked, cases.length);
  });

  test('the lines always sum to the totals', () {
    // The invariant a customer checks: the figures printed above the total add
    // up to the total. Asserted across the whole fixture rather than on one
    // hand-picked cart.
    for (final raw in cases) {
      final testCase = raw as Map<String, dynamic>;
      final lines = [
        for (final line in testCase['lines'] as List<dynamic>)
          LineInput(
            itemId: line['item_id'] as String,
            name: line['name'] as String,
            unitPriceCents: line['unit_price_cents'] as int,
            quantityMilli: line['quantity_milli'] as int,
            taxRateBps: line['tax_rate_bps'] as int,
            taxIsInclusive: line['tax_is_inclusive'] as bool,
            discountBps: line['discount_bps'] as int,
            discountCents: line['discount_cents'] as int,
          ),
      ];

      final totals = priceCart(
        lines,
        cartDiscountBps: testCase['cart_discount_bps'] as int,
        cartDiscountCents: testCase['cart_discount_cents'] as int,
      );

      expect(
        totals.lines.fold<int>(0, (sum, line) => sum + line.grossCents),
        totals.totalCents,
      );
      expect(
        totals.lines.fold<int>(0, (sum, line) => sum + line.netCents),
        totals.subtotalCents,
      );
      expect(
        totals.lines.fold<int>(0, (sum, line) => sum + line.taxCents),
        totals.taxCents,
      );
      // Net plus tax is exactly what the customer pays, on every line. This is
      // why inclusive tax is derived by subtraction rather than computed.
      for (final line in totals.lines) {
        expect(line.netCents + line.taxCents, line.grossCents);
      }
    }
  });
}
