# Generated by Django 5.2.17 on 2026-08-13 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(blank=True, help_text='Who acted, captured as text at the time. Survives the user record being renamed or removed, which is the whole point of an audit trail.', max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('DEACTIVATE', 'Deactivated'), ('REACTIVATE', 'Reactivated'), ('LOGIN', 'Signed in'), ('LOGIN_FAILED', 'Sign-in refused'), ('SUSPEND', 'Suspended'), ('STOCK_ADJUST', 'Stock adjusted'), ('VOID', 'Voided'), ('REFUND', 'Refunded')], max_length=32)),
                ('entity_type', models.CharField(help_text="Model label, for example 'catalog.Item'.", max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True, help_text='Free text supplied by the actor. Required for stock adjustments and voids.')),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the actor was deleted or the action was automated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for platform-level actions that predate or outlive a tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'core_audit_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='core_audit__tenant__985477_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_audit__entity__b88b7f_idx')],
            },
        ),
        # Tenant isolation is enforced by the database, not only by application
        # code. Without these policies a forgotten queryset filter would return
        # another business's rows. See apps/core/db/rls.py.
        *enable_rls_for("core_audit_log"),
    ]
