# Generated by Django 5.2.17 on 2026-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rls_on_indirectly_owned_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('DEACTIVATE', 'Deactivated'), ('REACTIVATE', 'Reactivated'), ('LOGIN', 'Signed in'), ('LOGIN_FAILED', 'Sign-in refused'), ('SUSPEND', 'Suspended'), ('STOCK_ADJUST', 'Stock adjusted'), ('VOID', 'Voided'), ('REFUND', 'Refunded'), ('DISCOUNT_AUTHORIZED', 'Discount authorised'), ('DISCOUNT_REFUSED', 'Discount authorisation refused')], max_length=32),
        ),
    ]
