# Generated by Django 5.2.17 on 2026-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('DEACTIVATE', 'Deactivated'), ('REACTIVATE', 'Reactivated'), ('LOGIN', 'Signed in'), ('LOGIN_FAILED', 'Sign-in refused'), ('SUSPEND', 'Suspended'), ('STOCK_ADJUST', 'Stock adjusted'), ('VOID', 'Voided'), ('REFUND', 'Refunded'), ('DISCOUNT_AUTHORIZED', 'Discount authorised'), ('DISCOUNT_REFUSED', 'Discount authorisation refused'), ('SHIFT_OPENED', 'Shift opened'), ('SHIFT_CLOSED', 'Shift closed'), ('CASH_MOVEMENT', 'Cash moved in or out of the drawer'), ('ORDER_VOID_REFUSED', 'Order void authorisation refused'), ('COMPLIANCE_MODE_CHANGED', 'Tax regime changed'), ('COMPLIANCE_MODE_UNKNOWN', 'Tax regime not recognised; nothing was submitted')], max_length=32),
        ),
    ]
