"""
The wire shapes for offline sync.

A till that has been off the network is not sending one sale, it is sending a
backlog. So the request is a batch and the response is a *per-sale verdict*,
not a single status code: one bad sale in a batch of forty must not strand the
other thirty-nine, and the till needs to know precisely which rows it may now
delete from its outbox.
"""

from __future__ import annotations

from rest_framework import serializers

from apps.sales.serializers import CheckoutLineSerializer


class OfflineAuthorizationSerializer(serializers.Serializer):
    """A discount the device approved while it had no connection.

    No PIN and no password. The device has already done the check against its
    cached copy, and the raw credential must not travel here afterwards - a
    replayed batch would then be a bundle of manager PINs in flight, which is
    strictly worse than the problem it would be solving.

    What travels instead is ``pin_version``: which version of that manager's
    PIN the cached copy was. See :func:`apps.sync.services.check_pin_version`
    for exactly what comparing it does and does not establish.
    """

    username = serializers.CharField(
        max_length=64, help_text="The manager whose cached PIN the device checked."
    )
    reason = serializers.CharField(max_length=500)
    pin_version = serializers.IntegerField(
        min_value=0,
        help_text=(
            "The version of that manager's PIN the device's cached copy was. A "
            "counter, not a digest - it carries no information about the PIN."
        ),
    )
    authorized_at = serializers.DateTimeField(
        help_text="When the device recorded the approval, by its own clock."
    )


class OfflineSaleSerializer(serializers.Serializer):
    """One sale rung up offline, as its till stored it.

    ``client_uuid`` is required here, unlike at the online till. Offline is
    exactly the situation where a request gets retried - the connection came
    back mid-upload, the app was killed, the batch was sent twice - so the key
    that makes a replay safe cannot be optional.
    """

    client_uuid = serializers.UUIDField(
        help_text="Generated by the till when the sale was rung up. The idempotency key."
    )
    device_sequence = serializers.IntegerField(
        required=False,
        allow_null=True,
        min_value=1,
        help_text="Monotonic per till, so a gap in a till's own series is visible.",
    )
    device_created_at = serializers.DateTimeField(
        help_text=(
            "When the till recorded it, by the till's clock. Kept for the "
            "shop's own reading of the day; never used for reporting, which "
            "goes by server_received_at so a wrong clock cannot move revenue."
        )
    )

    lines = CheckoutLineSerializer(many=True)

    cart_discount_bps = serializers.IntegerField(
        required=False, default=0, min_value=0, max_value=10_000
    )
    cart_discount_cents = serializers.IntegerField(required=False, default=0, min_value=0)
    discount_authorization = OfflineAuthorizationSerializer(required=False)

    tendered_cents = serializers.IntegerField(
        min_value=0, help_text="What the customer handed over. Offline sales are cash."
    )
    round_to_shilling = serializers.BooleanField(default=True)

    store_id = serializers.UUIDField(required=False, allow_null=True)
    customer_phone = serializers.CharField(max_length=32, required=False, allow_blank=True)
    note = serializers.CharField(required=False, allow_blank=True)

    total_cents = serializers.IntegerField(
        required=False,
        allow_null=True,
        help_text=(
            "What the till believed the sale came to. Never trusted - the "
            "server prices the cart again from the catalogue. Sent so that a "
            "disagreement can be recorded and looked at, which is how a "
            "stale price list on a till gets noticed."
        ),
    )

    def validate_lines(self, value):
        if not value:
            raise serializers.ValidationError("A sale needs at least one item.")
        return value


class OfflineRefusalSerializer(serializers.Serializer):
    """A discount authorisation the device refused while offline.

    Sent so that the shop's audit trail contains the failures as well as the
    successes. Without this, someone could stand at a disconnected till working
    through a manager's four digits and the only record would be on the tablet
    in their hand.
    """

    username = serializers.CharField(max_length=64, allow_blank=True)
    reason_code = serializers.ChoiceField(
        choices=[
            "no_authorization",
            "unknown_user",
            "bad_credential",
            "insufficient_role",
            "locked_out",
        ]
    )
    occurred_at = serializers.DateTimeField()


#: How many sales one request may carry.
#:
#: A till that has been off the network for a week has a backlog, not a
#: trickle - but the whole batch is written inside one request, and an
#: unbounded one would hold a transaction open for as long as it took. Two
#: hundred is a busy day at a counter, so a till with more than that sends
#: several requests and each one is independently safe to retry.
MAX_SALES_PER_BATCH = 200

#: Refusals are cheap rows, but the same reasoning applies.
MAX_REFUSALS_PER_BATCH = 500


class SyncBatchSerializer(serializers.Serializer):
    """A till emptying its outbox."""

    device_id = serializers.UUIDField(
        help_text="Which till these were rung up on. Must belong to this business."
    )
    sales = OfflineSaleSerializer(
        many=True, required=False, default=list, max_length=MAX_SALES_PER_BATCH
    )
    refused_authorizations = OfflineRefusalSerializer(
        many=True, required=False, default=list, max_length=MAX_REFUSALS_PER_BATCH
    )

    def validate(self, attrs: dict) -> dict:
        if not attrs.get("sales") and not attrs.get("refused_authorizations"):
            raise serializers.ValidationError("Nothing to sync.")
        return attrs


class CatalogItemSerializer(serializers.Serializer):
    """An item as a till caches it, flattened for offline pricing.

    Deliberately not the catalogue's own serializer. This is the subset a till
    needs to price a cart with no connection, and pinning it here means a field
    added for the back office does not silently enlarge every till's download.
    """

    id = serializers.UUIDField()
    name = serializers.CharField()
    sku = serializers.CharField()
    barcodes = serializers.ListField(child=serializers.CharField())
    unit = serializers.CharField()
    price_cents = serializers.IntegerField()
    is_price_variable = serializers.BooleanField()
    tax_rate_bps = serializers.IntegerField()
    tax_is_inclusive = serializers.BooleanField()
    is_active = serializers.BooleanField()
    updated_at = serializers.DateTimeField()


class CatalogStaffSerializer(serializers.Serializer):
    """A member of staff as a till caches them.

    ``pin_version`` travels so that an authorisation made against this cached
    copy can be matched, at sync, to the copy the server holds now.

    ``pin_hash`` travels because an offline check has to verify against
    something, and it is sent **only for users who can actually authorise a
    discount** - a cashier's hash is never downloaded, because no offline check
    would ever consult it.

    Understand what this costs, because it is not nothing. A PIN is four to six
    digits, so a hash of one is brute-forceable by anyone holding the tablet:
    a stolen till is, for practical purposes, a stolen manager PIN. That is
    inherent to approving anything offline against a short secret - a local
    check needs a local verifier - and the compensating controls are that the
    approval is recorded as ``OFFLINE`` rather than equated with a live one,
    that the PIN version is compared at sync, that refusals sync too, and that
    a lost till is revoked. See ARCHITECTURE.md, which also records the
    stronger fix this defers: a separate offline approval code, revocable on
    its own and useless for signing in.
    """

    id = serializers.UUIDField()
    username = serializers.CharField()
    full_name = serializers.CharField()
    role = serializers.CharField()
    pin_hash = serializers.CharField()
    pin_version = serializers.IntegerField()
    is_active = serializers.BooleanField()
    updated_at = serializers.DateTimeField()
