# Generated by Django 5.2.17 on 2026-08-14 20:11

import django.db.models.deletion

from apps.core.db.rls import enable_rls_for
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_pin_version'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, help_text="Generated by the till when the shift is opened, so a shift opened with no connection can be replayed exactly once. Unique per business, the same way a sale's is.", null=True)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float_cents', models.BigIntegerField(default=0, help_text='Counted cash placed in the drawer at the start, to give change from.')),
                ('declared_closing_cents', models.BigIntegerField(blank=True, help_text='What the cashier counted. Entered before they are shown the expectation.', null=True)),
                ('expected_closing_cents', models.BigIntegerField(blank=True, help_text='What the drawer should have held, computed once at close and never again. A later-arriving sale raises a discrepancy rather than changing this.', null=True)),
                ('variance_cents', models.BigIntegerField(blank=True, help_text='Declared minus expected. Negative is short, positive is over. Never blocks a close - the count is a fact to record, and a shop that cannot close its till stops trading.', null=True)),
                ('opening_note', models.TextField(blank=True)),
                ('closing_note', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(help_text='Who is accountable for this drawer. PROTECT, so the name survives.', on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, help_text="Usually the cashier. A manager closing somebody else's drawer - because they went home - is recorded here and audited as such.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, help_text='Which till. A drawer belongs to a counter, not to a person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='accounts.device')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'shifts_shift',
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='DrawerCount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denomination_cents', models.IntegerField(help_text='The note or coin, in cents. 100000 is a thousand-shilling note.')),
                ('quantity', models.PositiveIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='shifts.shift')),
            ],
            options={
                'db_table': 'shifts_drawer_count',
                'ordering': ('-denomination_cents',),
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PAID_IN', 'Cash put in'), ('PAID_OUT', 'Cash taken out'), ('DROP', 'Moved to the safe')], max_length=10)),
                ('amount_cents', models.BigIntegerField(help_text='Always positive. The kind decides the direction.')),
                ('reason', models.TextField(help_text="Required. 'Cash out' with no reason is indistinguishable from theft.")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='shifts.shift')),
            ],
            options={
                'db_table': 'shifts_cash_movement',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShiftDiscrepancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('VARIANCE', 'The count did not match the expectation'), ('LATE_ATTRIBUTION', 'A sale arrived after its shift had been closed'), ('FORCED_CLOSE', "A manager closed somebody else's drawer")], max_length=20)),
                ('detail', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_shift_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='shifts.shift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'shifts_discrepancy',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['tenant', 'state', '-opened_at'], name='shifts_shif_tenant__19bc32_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['tenant', 'store', '-opened_at'], name='shifts_shif_tenant__05ebff_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('tenant', 'client_uuid'), name='unique_shift_client_uuid_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'OPEN')), fields=('tenant', 'cashier'), name='one_open_shift_per_cashier'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_float_cents__gte', 0)), name='shift_float_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='drawercount',
            constraint=models.UniqueConstraint(fields=('shift', 'denomination_cents'), name='one_row_per_denomination_per_shift'),
        ),
        migrations.AddConstraint(
            model_name='drawercount',
            constraint=models.CheckConstraint(condition=models.Q(('denomination_cents__gt', 0)), name='denomination_is_positive'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['tenant', 'shift'], name='shifts_cash_tenant__e4b5d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='cash_movement_is_positive'),
        ),
        migrations.AddIndex(
            model_name='shiftdiscrepancy',
            index=models.Index(fields=['tenant', 'resolved_at', '-created_at'], name='shifts_disc_tenant__f6b03e_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftdiscrepancy',
            index=models.Index(fields=['tenant', 'shift'], name='shifts_disc_tenant__63481d_idx'),
        ),
        # Every one of these tables carries money or the record of who counted
        # it, so each gets the same policy as the sales tables. The coverage
        # test walks TenantOwnedModel subclasses and fails the build if one is
        # missing, which is what stops a new table shipping unprotected.
        *enable_rls_for(
            "shifts_shift",
            "shifts_cash_movement",
            "shifts_drawer_count",
            "shifts_discrepancy",
        ),
    ]
