# Generated by Django 5.2.17 on 2026-08-13 10:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110)),
                ('display_order', models.PositiveIntegerField(default=0, help_text="Lower numbers appear first on the till's category buttons.")),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'catalog_category',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(help_text="The business's own code for this item. Unique within the business.", max_length=64)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Physical product'), ('SERVICE', 'Service')], default='PRODUCT', max_length=10)),
                ('unit', models.CharField(choices=[('EACH', 'Each'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Millilitre'), ('M', 'Metre'), ('HOUR', 'Hour')], default='EACH', max_length=6)),
                ('price_cents', models.BigIntegerField(help_text='Selling price in cents. Whether tax is included is decided by the tax rate.', validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_cents', models.BigIntegerField(default=0, help_text='What the business paid, in cents. Used for margin reporting, never shown to customers.', validators=[django.core.validators.MinValueValidator(0)])),
                ('track_stock', models.BooleanField(default=True, help_text='Off for services, and for prepared food that is made to order rather than counted. A business can mix both freely.')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='How long a service takes. Used for appointment booking; null for products.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'catalog_item',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False, help_text="The code printed on this shop's own shelf labels.")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.item')),
            ],
            options={
                'db_table': 'catalog_barcode',
                'ordering': ('-is_primary', 'code'),
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="As it appears on a receipt, e.g. 'VAT 16%'.", max_length=60)),
                ('rate_bps', models.PositiveIntegerField(help_text='Basis points. 1600 is 16%, 0 is zero-rated.', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_inclusive', models.BooleanField(default=True, help_text='True when the marked price already contains this tax, which is normal for Kenyan retail: the customer pays exactly the shelf price.')),
                ('is_default', models.BooleanField(default=False, help_text='Applied to new items when none is chosen.')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'catalog_tax_rate',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tax_rate',
            field=models.ForeignKey(blank=True, help_text='Null means not taxed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.taxrate'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_category_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='barcode',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_barcode_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tax_rate_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='one_default_tax_rate_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'is_active'], name='catalog_ite_tenant__cbbee0_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'name'], name='catalog_ite_tenant__1d8955_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='unique_item_sku_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('item_type', 'SERVICE'), ('track_stock', True), _negated=True), name='services_do_not_track_stock'),
        ),
        # Tenant isolation is enforced by the database, not only by application
        # code. Without these policies a forgotten queryset filter would return
        # another business's rows. See apps/core/db/rls.py.
        *enable_rls_for("catalog_category", "catalog_tax_rate", "catalog_item", "catalog_barcode"),
    ]
