# Generated by Django 5.2.17 on 2026-08-13 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True, help_text="Temporarily off-sale, and deliberately separate from is_active. 'Out of season', 'kitchen has run out' and 'stylist off today' are everyday states that must not require delisting an item and re-creating it."),
        ),
        migrations.AddField(
            model_name='item',
            name='is_price_variable',
            field=models.BooleanField(default=False, help_text='The cashier enters the price at the till, starting from the suggestion above. For services quoted on the day and for retail oddments such as damaged stock.'),
        ),
        migrations.AddField(
            model_name='item',
            name='short_name',
            field=models.CharField(blank=True, help_text='Label for till buttons and receipt lines, where the full name will not fit. Falls back to a truncated name when blank.', max_length=24),
        ),
        migrations.AddField(
            model_name='item',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the till. Ties fall back to name.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Delisted. An inactive item is gone from the till entirely and stays only so past sales still resolve.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_cents',
            field=models.BigIntegerField(help_text='Selling price in cents. Whether tax is included is decided by the tax rate. When is_price_variable is set this is a suggestion rather than the price charged.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
