# Generated by Django 5.2.17 on 2026-08-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_version',
            field=models.PositiveIntegerField(default=0, help_text='Bumped every time the PIN is set or cleared. A device caches this alongside the hash it verifies against offline and sends it back at sync, so an authorisation made against a PIN that has since been changed or revoked is detectable. Carries no information about the PIN itself - it is a counter, not a digest.'),
        ),
    ]
