# Generated by Django 5.2.17 on 2026-08-16 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for, enable_rls_via


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_item_options_item_image_item_is_available_and_more'),
        ('sales', '0008_alter_salediscrepancy_kind'),
        ('stores', '0001_initial'),
        ('tenants', '0002_tenant_compliance_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('min_choices', models.PositiveIntegerField(default=0, help_text='0 makes the group optional.')),
                ('max_choices', models.PositiveIntegerField(default=0, help_text='0 means no limit.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, related_name='modifier_groups', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'restaurant_modifier_group',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price_cents', models.BigIntegerField(default=0, help_text="What it adds. Zero for 'no onions', which the kitchen still needs told about even though the till does not care.")),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, help_text='Required when price_cents is above zero.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_as_modifier', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='restaurant.modifiergroup')),
            ],
            options={
                'db_table': 'restaurant_modifier',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('OPEN', 'Being taken'), ('SENT', 'Sent to the kitchen'), ('BILLED', 'Paid and closed'), ('VOID', 'Cancelled'), ('MERGED', 'Merged into another table')], default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('covers', models.PositiveIntegerField(default=0, help_text='How many people are eating. For per-head reporting later.')),
                ('note', models.TextField(blank=True)),
                ('void_reason', models.TextField(blank=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='restaurant.order')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_orders', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_order', to='sales.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'restaurant_order',
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(help_text='1, 2, 3 within one order. Printed so the kitchen can spot a gap.')),
                ('printed_at', models.DateTimeField()),
                ('reprint_count', models.PositiveIntegerField(default=0, help_text='How many times this was printed again. A kitchen that keeps asking for reprints is telling you something about the printer.')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='restaurant.order')),
            ],
            options={
                'db_table': 'restaurant_kitchen_ticket',
                'ordering': ('order', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=6)),
                ('base_price_cents', models.BigIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.TextField(blank=True, help_text="Free text for the kitchen. 'Well done', 'allergy - nuts'.")),
                ('is_voided', models.BooleanField(default=False, help_text='A line struck off before payment. Kept rather than deleted, because a line that reached the kitchen and was then cancelled is a thing somebody may need to explain.')),
                ('void_reason', models.TextField(blank=True)),
                ('first_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='restaurant.kitchenticket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='restaurant.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'restaurant_order_line',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLineModifier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price_cents', models.BigIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billed_as_modifier', to='catalog.item')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chosen', to='restaurant.modifier')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='restaurant.orderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'restaurant_order_line_modifier',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="How staff call it. 'Table 4', 'Terrace 2', 'Bar'.", max_length=40)),
                ('seats', models.PositiveIntegerField(default=0, help_text='Informational. Nothing refuses a party of five on a four-top.')),
                ('is_active', models.BooleanField(default=True, help_text='Tables are deactivated rather than deleted, so the orders that were served at one keep a name attached to them.')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'restaurant_table',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Null once merged away, so the emptied order keeps its history.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurant.table'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_modifier_group_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('max_choices', 0), ('max_choices__gte', models.F('min_choices')), _connector='OR'), name='modifier_max_not_below_min'),
        ),
        migrations.AddConstraint(
            model_name='modifier',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_modifier_per_group'),
        ),
        migrations.AddConstraint(
            model_name='modifier',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents', 0), ('item__isnull', False), _connector='OR'), name='priced_modifier_has_an_item'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['tenant', '-printed_at'], name='restaurant__tenant__e137fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='kitchenticket',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='unique_ticket_sequence_per_order'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['tenant', 'order'], name='restaurant__tenant__774b64_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['tenant', 'store', 'is_active'], name='restaurant__tenant__42e367_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('tenant', 'store', 'name'), name='unique_table_name_per_store'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'state', '-opened_at'], name='restaurant__tenant__0da42c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'table'], name='restaurant__tenant__914242_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('OPEN', 'SENT'))), fields=('tenant', 'table'), name='one_live_order_per_table'),
        ),
        # Six tables carrying a restaurant's trading, so each gets the same
        # policy as everything else. The coverage test walks TenantOwnedModel
        # subclasses and fails the build if one is missing.
        *enable_rls_for(
            "restaurant_table",
            "restaurant_order",
            "restaurant_order_line",
            "restaurant_modifier_group",
            "restaurant_modifier",
            "restaurant_order_line_modifier",
            "restaurant_kitchen_ticket",
        ),
        # Django creates the many-to-many join table itself, so it carries no
        # tenant column of its own and belongs to a business only through the
        # group it points at. The coverage test walks ownership transitively
        # and caught this, which is what that test exists for.
        enable_rls_via(
            "restaurant_modifier_group_items",
            "modifiergroup_id",
            "restaurant_modifier_group",
        ),
    ]
