# Generated by Django 5.2.17 on 2026-08-13 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Short identifier the till sends at sign-in. Entered once when a device is set up and remembered from then on, which is why usernames only need to be unique within a business.', max_length=60, unique=True)),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail shop'), ('RESTAURANT', 'Restaurant or bar'), ('SALON', 'Salon or services'), ('PHARMACY', 'Pharmacy')], default='RETAIL', max_length=20)),
                ('status', models.CharField(choices=[('TRIAL', 'On trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], db_index=True, default='TRIAL', max_length=20)),
                ('country', models.CharField(default='KE', max_length=2)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('vat_mode', models.CharField(choices=[('INCLUSIVE', 'Prices include tax'), ('EXCLUSIVE', 'Tax added at checkout'), ('PER_ITEM', 'Decided per item')], default='INCLUSIVE', max_length=20)),
                ('kra_pin', models.CharField(blank=True, help_text='Tax PIN printed on receipts and required for tax invoices.', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='tenant-logos/')),
                ('receipt_header', models.CharField(blank=True, max_length=200)),
                ('receipt_footer', models.CharField(blank=True, default='Thank you for your business', max_length=200)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('setup_completed_at', models.DateTimeField(blank=True, help_text='Set when the owner finishes the setup wizard. Guards it from being re-run.', null=True)),
                ('notes', models.TextField(blank=True, help_text="Platform operator's notes. Never shown to the tenant.")),
            ],
            options={
                'db_table': 'tenants_tenant',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_key', models.CharField(choices=[('stock', 'Stock tracking'), ('mpesa', 'M-Pesa payments'), ('compliance', 'Tax compliance and invoicing'), ('restaurant', 'Tables, orders and modifiers'), ('appointments', 'Appointment booking'), ('pharmacy_batches', 'Batch and expiry tracking')], max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Module-specific settings. Kept as JSON because each module owns its own shape and validates it in its own serializer.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_tenant_module',
                'ordering': ('module_key',),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'module_key'), name='unique_module_per_tenant')],
            },
        ),
        # Tenant isolation is enforced by the database, not only by application
        # code. Without these policies a forgotten queryset filter would return
        # another business's rows. See apps/core/db/rls.py.
        *enable_rls_for("tenants_tenant_module"),
    ]
