# Generated by Django 5.2.17 on 2026-08-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='compliance_mode',
            field=models.CharField(default='NONE', help_text="Which compliance adapter this business's tax documents go through. Defaults to NONE because most small dukas are not VAT-registered - that is the common case, not a stub for one. Choices live on apps.compliance.ComplianceMode; kept as a plain field here so tenants does not depend on compliance.", max_length=10),
        ),
    ]
