# Generated by Django 5.2.17 on 2026-08-13 21:05

import apps.payments.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkout_request_id', models.CharField(blank=True, max_length=64)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=32)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True)),
                ('amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('outcome', models.CharField(choices=[('APPLIED', 'Payment credited'), ('DUPLICATE', 'Already seen, ignored'), ('FAILED_PAYMENT', 'Customer did not pay'), ('SUSPECT', 'Held for a person to check')], max_length=16)),
                ('suspect_reason', models.CharField(blank=True, choices=[('UNKNOWN_TOKEN', 'No intent matches this callback URL'), ('REQUEST_ID_MISMATCH', 'Checkout request id does not match the intent'), ('AMOUNT_MISMATCH', 'Amount does not match the intent'), ('SALE_NOT_AWAITING', 'Sale is no longer awaiting payment'), ('UNTRUSTED_SOURCE', 'Came from an address not on the allowlist'), ('INTENT_ALREADY_SETTLED', 'Intent was already resolved')], max_length=24)),
                ('raw_payload', models.JSONField(default=dict, help_text='Exactly what Safaricom sent, kept for disputes and for replaying in tests.')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_callbacks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payments_mpesa_callback',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MpesaCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortcode', models.CharField(help_text='Paybill or till number money is paid into.', max_length=16)),
                ('consumer_key', apps.payments.fields.EncryptedTextField()),
                ('consumer_secret', apps.payments.fields.EncryptedTextField()),
                ('passkey', apps.payments.fields.EncryptedTextField(help_text='Used to sign the STK push password.')),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', help_text='Sandbox until Safaricom issues the business its production credentials, which happens on their timeline rather than ours.', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_callback_ips', models.JSONField(blank=True, default=list, help_text='Safaricom source addresses accepted for callbacks. Required on production, optional on sandbox where no real money moves.')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='When these credentials last successfully obtained a token.', null=True)),
                ('last_error', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payments_mpesa_credential',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Generated by the till before the request. Retrying with the same uuid returns this intent rather than sending a second prompt to the customer's phone.")),
                ('amount_cents', models.BigIntegerField()),
                ('phone', models.CharField(help_text='Where the prompt is sent.', max_length=32)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('callback_token', models.CharField(editable=False, help_text='Embedded in the callback URL sent to Safaricom. A callback carries no tenant, so this is what lets an unauthenticated request resolve to one business and one sale before anything is bound.', max_length=64, unique=True)),
                ('state', models.CharField(choices=[('PENDING', 'Waiting for the customer'), ('SUCCEEDED', 'Paid'), ('FAILED', 'Refused or cancelled'), ('EXPIRED', 'No answer in time')], db_index=True, default='PENDING', max_length=12)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(help_text='An STK prompt lapses in about a minute. Past this the intent stops blocking a retry, and the reconciliation job asks Safaricom what actually happened.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, help_text='When the outcome was confirmed by querying Daraja rather than by a callback.', null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_payment_intent',
                'ordering': ('-created_at',),
            },
        ),
        # Tenant isolation is enforced by the database, not only by
        # application code. These tables hold money, so a forgotten filter
        # here would be worse than one anywhere else in the system.
        *enable_rls_for(
            "payments_mpesa_credential",
            "payments_mpesa_callback",
        ),
        # payments_payment_intent is protected in 0002 instead. Its tenant
        # column does not exist yet: sales and payments reference each other,
        # so Django defers those foreign keys to a second migration, and a
        # policy naming tenant_id here would fail to apply.
    ]
