# Generated by Django 5.2.17 on 2026-08-13 21:05

import django.db.models.deletion
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mpesacallback',
            name='intent',
            field=models.ForeignKey(blank=True, help_text='Null when the callback token matched nothing at all.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='callbacks', to='payments.paymentintent'),
        ),
        migrations.AddConstraint(
            model_name='mpesacredential',
            constraint=models.UniqueConstraint(fields=('tenant',), name='one_mpesa_credential_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['tenant', 'state', '-created_at'], name='payments_pa_tenant__bc223b_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_uuid'), name='unique_intent_client_uuid_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_request_id', ''), _negated=True), fields=('tenant', 'checkout_request_id'), name='unique_checkout_request_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='mpesacallback',
            index=models.Index(fields=['tenant', 'outcome', '-created_at'], name='payments_mp_tenant__acb312_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallback',
            index=models.Index(fields=['outcome', 'resolved_at'], name='payments_mp_outcome_bc6609_idx'),
        ),
        migrations.AddConstraint(
            model_name='mpesacallback',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_request_id', ''), _negated=True), fields=('checkout_request_id',), name='unique_callback_per_checkout_request'),
        ),
        # Applied here rather than in 0001 because this is the migration
        # that adds the tenant column, the circular sales/payments foreign
        # keys having deferred it. The coverage test fails the build if a
        # table with a tenant ever ships without a policy.
        *enable_rls_for("payments_payment_intent"),
    ]
