"""
Sales, and the two ledgers that decide what state each one is in.

The shape here follows the discipline stock already uses. A sale's ``state`` is
a cache of its payment and refund ledgers, both append-only. Nothing is ever
mutated to record that money moved: a payment is a row, a refund is a row, and
the state falls out of summing them.

That matters more here than it did for stock, because these rows are money. An
editable payment would let someone alter what a customer paid after the fact; a
refund that mutated the original sale would erase the evidence that a reversal
happened at all.

Every amount is integer cents. Quantities are Decimal, because goods sold by
weight are real. See ``apps.core.money`` and ``apps.sales.pricing``.
"""

from __future__ import annotations

import uuid
from decimal import Decimal

from django.db import models

from apps.core.models import TenantOwnedModel, TimeStampedModel, UUIDModel
from apps.sales.states import SaleState


class PaymentMethod(models.TextChoices):
    """How money moved."""

    CASH = "CASH", "Cash"
    MPESA = "MPESA", "M-Pesa"


class RefundMethod(models.TextChoices):
    """How money was given back.

    ``MPESA_MANUAL`` records that a refund is owed and how it will be settled,
    without the system moving the money. Automated M-Pesa refunds need the B2C
    product, its own credentials and a funded float, which a small shop does not
    have on day one - so the ledger stays correct and the shop settles it the
    way they already do.
    """

    CASH = "CASH", "Cash"
    MPESA_MANUAL = "MPESA_MANUAL", "M-Pesa, sent separately"


class Sale(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """One transaction at a till."""

    # ---- Identity -------------------------------------------------------

    client_uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        help_text=(
            "Generated by the till before any network call. The idempotency key "
            "for sync: replaying a batch returns the original sale rather than "
            "creating a second one."
        ),
    )
    receipt_number = models.BigIntegerField(
        null=True,
        blank=True,
        help_text=(
            "Sequential per business, allocated when the sale completes. Gapless, "
            "because this is the series tax reporting will read."
        ),
    )
    receipt_code = models.CharField(
        max_length=40, blank=True, help_text="The formatted number printed on the receipt."
    )
    provisional_reference = models.CharField(
        max_length=40,
        blank=True,
        help_text=(
            "Printed by a till with no connection, which cannot allocate a "
            "business-wide number. Kept after sync so the paper in a customer's "
            "hand can still be matched to the fiscal number."
        ),
    )

    state = models.CharField(
        max_length=20,
        choices=SaleState.choices,
        default=SaleState.OPEN,
        db_index=True,
        help_text="Derived from the payment and refund ledgers. See sales/states.py.",
    )

    # ---- Where and who --------------------------------------------------

    store = models.ForeignKey("stores.Store", on_delete=models.PROTECT, related_name="sales")
    cashier = models.ForeignKey(
        "accounts.User",
        on_delete=models.PROTECT,
        related_name="sales",
        help_text="Who rang it up. PROTECT, so a sale always keeps a named person.",
    )
    device = models.ForeignKey(
        "accounts.Device",
        on_delete=models.SET_NULL,
        related_name="sales",
        null=True,
        blank=True,
    )
    device_sequence = models.BigIntegerField(
        null=True,
        blank=True,
        help_text="Monotonic per device, so a gap in a till's own series is visible.",
    )

    # ---- Money ----------------------------------------------------------

    subtotal_cents = models.BigIntegerField(default=0, help_text="Net of tax, after discounts.")
    discount_cents = models.BigIntegerField(
        default=0, help_text="Line and cart discounts together."
    )
    tax_cents = models.BigIntegerField(default=0)
    total_cents = models.BigIntegerField(default=0, help_text="What the customer owes.")

    cart_discount_bps = models.PositiveIntegerField(default=0)
    cart_discount_cents = models.BigIntegerField(default=0)

    rounding_adjustment_cents = models.IntegerField(
        default=0,
        help_text=(
            "Cash rounds to the shilling because no smaller coin circulates. The "
            "difference is recorded so the drawer reconciles exactly rather than "
            "drifting a few shillings a day."
        ),
    )

    is_overpaid = models.BooleanField(
        default=False,
        help_text=(
            "More was taken than was owed, which two successful M-Pesa pushes "
            "genuinely can do. Blocks completion until a manager refunds the "
            "difference; the money is real and discarding the record would be "
            "worse than surfacing it."
        ),
    )

    # ---- Provenance -----------------------------------------------------

    device_created_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the till recorded it. May be well before it reached the server.",
    )
    server_received_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=(
            "When the server first saw it. All reporting uses this: a till "
            "with a wrong clock must not move revenue between days."
        ),
    )
    was_offline = models.BooleanField(
        default=False, help_text="Rung up with no connection and synced later."
    )

    customer_phone = models.CharField(max_length=32, blank=True)
    note = models.TextField(blank=True)
    void_reason = models.TextField(blank=True)

    class Meta:
        db_table = "sales_sale"
        ordering = ("-created_at",)
        constraints = [
            # The idempotency key that makes a retried sync safe.
            models.UniqueConstraint(
                fields=["tenant", "client_uuid"], name="unique_sale_client_uuid_per_tenant"
            ),
            # Gapless per business, and enforced rather than merely intended.
            models.UniqueConstraint(
                fields=["tenant", "receipt_number"],
                condition=models.Q(receipt_number__isnull=False),
                name="unique_receipt_number_per_tenant",
            ),
            models.CheckConstraint(
                condition=models.Q(total_cents__gte=0), name="sale_total_not_negative"
            ),
        ]
        indexes = [
            models.Index(fields=["tenant", "state", "-created_at"]),
            models.Index(fields=["tenant", "store", "-created_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.receipt_code or self.provisional_reference or self.pk} ({self.state})"

    @property
    def is_editable(self) -> bool:
        """Whether lines may still be changed. Only while open."""
        from apps.sales.states import EDITABLE_STATES

        return self.state in EDITABLE_STATES

    @property
    def amount_due_cents(self) -> int:
        """What the customer pays, after cash rounding."""
        return self.total_cents + self.rounding_adjustment_cents


class SaleLine(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """One line of a sale, with everything about it frozen at the time of sale.

    The snapshot is the point. Name, price, discount, tax rate *and* whether that
    rate was inclusive are all copied here rather than read through the item, so
    a price change or a VAT change tomorrow cannot retroactively rewrite a
    receipt a customer is holding.
    """

    sale = models.ForeignKey(Sale, on_delete=models.PROTECT, related_name="lines")
    item = models.ForeignKey(
        "catalog.Item",
        on_delete=models.PROTECT,
        related_name="sale_lines",
        help_text="Kept for reporting. Nothing is read through it at display time.",
    )

    # Snapshot at the moment of sale.
    name = models.CharField(max_length=150)
    sku = models.CharField(max_length=64)
    unit = models.CharField(max_length=6)
    unit_price_cents = models.BigIntegerField()
    quantity = models.DecimalField(max_digits=12, decimal_places=3)

    line_discount_cents = models.BigIntegerField(default=0)
    cart_discount_share_cents = models.BigIntegerField(
        default=0, help_text="This line's share of a whole-cart discount, apportioned before tax."
    )

    tax_rate_bps = models.PositiveIntegerField(default=0)
    tax_is_inclusive = models.BooleanField(default=True)

    net_cents = models.BigIntegerField(help_text="Taxable base after discounts.")
    tax_cents = models.BigIntegerField(default=0)
    gross_cents = models.BigIntegerField(help_text="What this line adds to the total.")

    position = models.PositiveIntegerField(default=0, help_text="Order on the receipt.")

    class Meta:
        db_table = "sales_sale_line"
        ordering = ("position", "created_at")
        indexes = [models.Index(fields=["sale", "position"])]

    def __str__(self) -> str:
        return f"{self.quantity} x {self.name}"

    @property
    def total_discount_cents(self) -> int:
        return self.line_discount_cents + self.cart_discount_share_cents


class Payment(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """Money taken. Append-only.

    Never edited and never deleted. A correction is a refund, which is its own
    row - so the record of what a customer actually handed over survives any
    later change of mind.

    Split payments are simply several rows against one sale; part cash and part
    M-Pesa needs no special case.
    """

    sale = models.ForeignKey(Sale, on_delete=models.PROTECT, related_name="payments")
    method = models.CharField(max_length=10, choices=PaymentMethod.choices)
    amount_cents = models.BigIntegerField(help_text="Applied to the sale.")

    tendered_cents = models.BigIntegerField(
        default=0, help_text="What was physically handed over, for cash."
    )
    change_cents = models.BigIntegerField(default=0)

    # M-Pesa specifics. The receipt number is the identifier of a real money
    # movement, so it is unique per business: no path may credit one twice.
    mpesa_receipt_number = models.CharField(max_length=32, blank=True)
    mpesa_phone = models.CharField(max_length=32, blank=True)
    intent = models.ForeignKey(
        "payments.PaymentIntent",
        on_delete=models.SET_NULL,
        related_name="payments",
        null=True,
        blank=True,
    )

    user = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        related_name="payments_taken",
        null=True,
        blank=True,
        help_text="Who took it. Null only for a payment applied by an M-Pesa callback.",
    )

    class Meta:
        db_table = "sales_payment"
        ordering = ("created_at",)
        constraints = [
            models.UniqueConstraint(
                fields=["tenant", "mpesa_receipt_number"],
                condition=~models.Q(mpesa_receipt_number=""),
                name="unique_mpesa_receipt_per_tenant",
            ),
            models.CheckConstraint(
                condition=models.Q(amount_cents__gt=0), name="payment_amount_positive"
            ),
        ]
        indexes = [models.Index(fields=["tenant", "-created_at"])]

    def __str__(self) -> str:
        return f"{self.method} {self.amount_cents}"


class Refund(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """Money given back. Append-only, like a payment.

    A refund is a new document referencing the sale, never a mutation of it. A
    partial refund followed by another is two rows, and the sale's state is the
    sum - so the history of what was returned and when survives intact.
    """

    sale = models.ForeignKey(Sale, on_delete=models.PROTECT, related_name="refunds")
    method = models.CharField(max_length=16, choices=RefundMethod.choices)
    amount_cents = models.BigIntegerField()

    reason = models.TextField(
        help_text="Required. Nothing is given back without an explanation on the record."
    )
    user = models.ForeignKey(
        "accounts.User",
        on_delete=models.PROTECT,
        related_name="refunds_given",
        help_text="Manager or owner. PROTECT, so the authoriser cannot be removed.",
    )

    is_settled = models.BooleanField(
        default=True,
        help_text=(
            "False while an M-Pesa refund is recorded but not yet sent, so money "
            "owed to a customer is visible rather than assumed done."
        ),
    )

    class Meta:
        db_table = "sales_refund"
        ordering = ("-created_at",)
        constraints = [
            models.CheckConstraint(
                condition=models.Q(amount_cents__gt=0), name="refund_amount_positive"
            )
        ]
        indexes = [models.Index(fields=["tenant", "-created_at"])]

    def __str__(self) -> str:
        return f"Refund {self.amount_cents} on {self.sale_id}"


class RefundLine(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """What was returned, line by line."""

    refund = models.ForeignKey(Refund, on_delete=models.CASCADE, related_name="lines")
    sale_line = models.ForeignKey(SaleLine, on_delete=models.PROTECT, related_name="refund_lines")

    quantity = models.DecimalField(max_digits=12, decimal_places=3)
    amount_cents = models.BigIntegerField()

    restock = models.BooleanField(
        default=True,
        help_text=(
            "Whether the goods go back on the shelf. False for something returned "
            "damaged, which is refunded but cannot be sold again."
        ),
    )

    class Meta:
        db_table = "sales_refund_line"
        ordering = ("created_at",)
        constraints = [
            models.CheckConstraint(
                condition=models.Q(quantity__gt=Decimal("0")), name="refund_line_quantity_positive"
            )
        ]

    def __str__(self) -> str:
        return f"{self.quantity} x {self.sale_line_id}"


class ReceiptCounter(TenantOwnedModel, TimeStampedModel):
    """The last receipt number issued to a business.

    One row per business. Locked for the duration of each allocation, which is
    what makes the series gapless rather than merely unique.
    """

    last_number = models.BigIntegerField(default=0)
    prefix = models.CharField(
        max_length=12,
        default="INV",
        help_text="Printed before the number, e.g. INV-2026-000001.",
    )

    class Meta:
        db_table = "sales_receipt_counter"
        constraints = [
            models.UniqueConstraint(fields=["tenant"], name="one_receipt_counter_per_tenant")
        ]

    def __str__(self) -> str:
        return f"{self.prefix}: {self.last_number}"


class SaleDiscrepancy(TenantOwnedModel, UUIDModel, TimeStampedModel):
    """Something about a sale that a person needs to look at.

    Sales are never rejected for these - the money already moved. They are
    recorded and surfaced, exactly as a stock adjustment that goes negative is
    surfaced rather than refused.
    """

    class Kind(models.TextChoices):
        TOTALS_MISMATCH = "TOTALS_MISMATCH", "Device totals disagree with the server"
        NEGATIVE_STOCK = "NEGATIVE_STOCK", "Sale drove stock below zero"
        OVERPAID = "OVERPAID", "More was taken than was owed"
        LATE_PAYMENT = "LATE_PAYMENT", "Payment arrived after the sale was finished"

    sale = models.ForeignKey(
        Sale, on_delete=models.PROTECT, related_name="discrepancies", null=True, blank=True
    )
    kind = models.CharField(max_length=20, choices=Kind.choices)
    detail = models.TextField()
    context = models.JSONField(default=dict, blank=True)

    resolved_at = models.DateTimeField(null=True, blank=True)
    resolved_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        related_name="resolved_discrepancies",
        null=True,
        blank=True,
    )
    resolution_note = models.TextField(blank=True)

    class Meta:
        db_table = "sales_discrepancy"
        ordering = ("-created_at",)
        indexes = [models.Index(fields=["tenant", "resolved_at", "-created_at"])]

    def __str__(self) -> str:
        return f"{self.kind} on {self.sale_id}"

    @property
    def is_open(self) -> bool:
        return self.resolved_at is None
