"""
Serializers for checkout.

These shape requests and responses. They do not price anything and they do not
decide state - ``apps.sales.services`` owns both, and duplicating either here
would create a second implementation to keep in step.
"""

from __future__ import annotations

from decimal import Decimal

from rest_framework import serializers

from apps.sales.models import Payment, Refund, Sale, SaleLine


class DiscountAuthorizationSerializer(serializers.Serializer):
    """A manager approving a cashier's discount, at the till, right now.

    Only needed when the person ringing up is a cashier. A manager or owner
    authorises from their own session and sends nothing here.

    The credential is verified and discarded; nothing is signed in and no token
    is issued. It is write-only so it cannot come back in a response, and it is
    never stored.
    """

    # Optional at this layer on purpose. Whether a username is needed depends
    # on the acting user's role, and that rule lives in
    # apps.sales.authorization - a manager ringing up sends only a reason.
    # Encoding the rule here as well would give it two homes and one of them
    # would eventually be wrong.
    username = serializers.CharField(
        max_length=64,
        required=False,
        allow_blank=True,
        help_text=(
            "The manager approving this, within this business. Required only "
            "when a cashier is ringing up; a manager authorises from their own "
            "session."
        ),
    )
    pin = serializers.CharField(
        write_only=True, required=False, allow_blank=True, help_text="Their till PIN."
    )
    password = serializers.CharField(
        write_only=True,
        required=False,
        allow_blank=True,
        help_text="Their password, if they would rather not use a PIN.",
    )
    reason = serializers.CharField(
        max_length=500, help_text="Why the discount is being given. Required."
    )


class CheckoutLineSerializer(serializers.Serializer):
    """One line as the till submits it."""

    item_id = serializers.UUIDField()
    quantity = serializers.DecimalField(max_digits=12, decimal_places=3)
    unit_price_cents = serializers.IntegerField(
        required=False,
        allow_null=True,
        help_text=(
            "Only consulted for items marked as variable-priced, and only at or "
            "above their marked price. Ignored entirely otherwise: the "
            "catalogue is the source of every ordinary price."
        ),
    )
    discount_bps = serializers.IntegerField(
        required=False, default=0, min_value=0, max_value=10_000
    )
    discount_cents = serializers.IntegerField(required=False, default=0, min_value=0)

    def validate_quantity(self, value: Decimal) -> Decimal:
        if value <= 0:
            raise serializers.ValidationError("A quantity must be more than zero.")
        return value


class CashCheckoutSerializer(serializers.Serializer):
    """Ring up a sale and settle it in cash, in one request.

    One request rather than create-then-pay because that is how a counter
    works: the cashier scans, takes the money and hands over a receipt as a
    single act. Two requests would leave an OPEN sale stranded whenever the
    connection dropped between them.
    """

    lines = CheckoutLineSerializer(many=True)

    cart_discount_bps = serializers.IntegerField(
        required=False, default=0, min_value=0, max_value=10_000
    )
    cart_discount_cents = serializers.IntegerField(
        required=False, default=0, min_value=0
    )
    discount_authorization = DiscountAuthorizationSerializer(required=False)

    tendered_cents = serializers.IntegerField(
        min_value=0, help_text="What the customer handed over."
    )
    round_to_shilling = serializers.BooleanField(
        default=True,
        help_text=(
            "Cash rounds to the shilling because no smaller coin circulates. "
            "The difference is recorded on the sale so the drawer reconciles."
        ),
    )

    store_id = serializers.UUIDField(required=False, allow_null=True)
    client_uuid = serializers.UUIDField(
        required=False,
        allow_null=True,
        help_text="Generated by the till, so a retried request cannot create a second sale.",
    )
    customer_phone = serializers.CharField(max_length=32, required=False, allow_blank=True)
    note = serializers.CharField(required=False, allow_blank=True)

    def validate_lines(self, value):
        if not value:
            raise serializers.ValidationError("A sale needs at least one item.")
        return value

    def validate(self, attrs: dict) -> dict:
        """Refuse a discount with no authorisation before anything is created.

        Checked here as well as in the authorisation module so the caller gets a
        field-level error rather than a generic refusal, and so nothing is
        written before the question of authority is settled.
        """
        has_line_discount = any(
            line.get("discount_bps") or line.get("discount_cents") for line in attrs["lines"]
        )
        has_cart_discount = bool(
            attrs.get("cart_discount_bps") or attrs.get("cart_discount_cents")
        )
        attrs["_has_discount"] = has_line_discount or has_cart_discount
        return attrs


class MpesaCheckoutSerializer(serializers.Serializer):
    """Ring up a sale and send a payment prompt to the customer's phone.

    Deliberately the same shape as the cash request, minus the tender and plus
    a phone number. A discount needs authority here in exactly the same way -
    putting M-Pesa on its own surface is how a gate ends up enforced on one path
    and quietly not on the other.
    """

    lines = CheckoutLineSerializer(many=True)

    cart_discount_bps = serializers.IntegerField(
        required=False, default=0, min_value=0, max_value=10_000
    )
    cart_discount_cents = serializers.IntegerField(
        required=False, default=0, min_value=0
    )
    discount_authorization = DiscountAuthorizationSerializer(required=False)

    phone = serializers.CharField(
        max_length=32,
        help_text=(
            "The customer's number. Accepted as 07..., +254..., 254... or "
            "7... - a cashier should not have to reformat while someone waits."
        ),
    )

    store_id = serializers.UUIDField(required=False, allow_null=True)
    client_uuid = serializers.UUIDField(required=False, allow_null=True)
    payment_client_uuid = serializers.UUIDField(
        required=False,
        allow_null=True,
        help_text=(
            "Generated by the till for this payment attempt. Retrying with the "
            "same value returns the existing attempt instead of sending a "
            "second prompt to the customer's phone."
        ),
    )
    note = serializers.CharField(required=False, allow_blank=True)

    def validate_lines(self, value):
        if not value:
            raise serializers.ValidationError("A sale needs at least one item.")
        return value

    def validate(self, attrs: dict) -> dict:
        has_line_discount = any(
            line.get("discount_bps") or line.get("discount_cents") for line in attrs["lines"]
        )
        has_cart_discount = bool(
            attrs.get("cart_discount_bps") or attrs.get("cart_discount_cents")
        )
        attrs["_has_discount"] = has_line_discount or has_cart_discount
        return attrs


class PaymentIntentSerializer(serializers.Serializer):
    """A payment prompt the customer has been sent."""

    id = serializers.UUIDField(read_only=True)
    state = serializers.CharField(read_only=True)
    amount_cents = serializers.IntegerField(read_only=True)
    phone = serializers.CharField(read_only=True)
    checkout_request_id = serializers.CharField(read_only=True)
    expires_at = serializers.DateTimeField(read_only=True)
    created_at = serializers.DateTimeField(read_only=True)


class SaleLineSerializer(serializers.ModelSerializer):
    """A line as it appears on a receipt: everything frozen at the time of sale."""

    total_discount_cents = serializers.IntegerField(read_only=True)

    class Meta:
        model = SaleLine
        fields = (
            "id",
            "item",
            "name",
            "sku",
            "unit",
            "unit_price_cents",
            "quantity",
            "line_discount_cents",
            "cart_discount_share_cents",
            "total_discount_cents",
            "tax_rate_bps",
            "tax_is_inclusive",
            "net_cents",
            "tax_cents",
            "gross_cents",
            "position",
        )
        read_only_fields = fields


class PaymentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Payment
        fields = (
            "id",
            "method",
            "amount_cents",
            "tendered_cents",
            "change_cents",
            "mpesa_receipt_number",
            "created_at",
        )
        read_only_fields = fields


class RefundSerializer(serializers.ModelSerializer):
    authorized_by = serializers.CharField(source="user.username", read_only=True)

    class Meta:
        model = Refund
        fields = (
            "id",
            "method",
            "amount_cents",
            "reason",
            "authorized_by",
            "is_settled",
            "created_at",
        )
        read_only_fields = fields


class SaleSerializer(serializers.ModelSerializer):
    """A sale as the till and the receipt need it."""

    lines = SaleLineSerializer(many=True, read_only=True)
    payments = PaymentSerializer(many=True, read_only=True)
    refunds = RefundSerializer(many=True, read_only=True)

    cashier_name = serializers.CharField(source="cashier.full_name", read_only=True)
    store_code = serializers.CharField(source="store.code", read_only=True)
    amount_due_cents = serializers.IntegerField(read_only=True)
    change_cents = serializers.SerializerMethodField()

    class Meta:
        model = Sale
        fields = (
            "id",
            "client_uuid",
            "receipt_number",
            "receipt_code",
            "provisional_reference",
            "state",
            "store",
            "store_code",
            "cashier",
            "cashier_name",
            "subtotal_cents",
            "discount_cents",
            "tax_cents",
            "total_cents",
            "rounding_adjustment_cents",
            "amount_due_cents",
            "change_cents",
            "is_overpaid",
            "discount_authorized_label",
            "discount_authorization_reason",
            "discount_authorized_via",
            "discount_authorized_at",
            "customer_phone",
            "note",
            "was_offline",
            "device_created_at",
            "server_received_at",
            "created_at",
            "lines",
            "payments",
            "refunds",
        )
        read_only_fields = fields

    def get_change_cents(self, obj: Sale) -> int:
        """Change handed back, summed from the payments that gave it."""
        return sum(payment.change_cents for payment in obj.payments.all())
