# Generated by Django 5.2.17 on 2026-08-13 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text="Short label used on receipts and reports, for example 'MAIN'.", max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Where sales are recorded when a till has not been told otherwise. Exactly one per business.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'stores_store',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_store_code_per_tenant'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='one_default_store_per_tenant')],
            },
        ),
        # Tenant isolation is enforced by the database, not only by application
        # code. Without these policies a forgotten queryset filter would return
        # another business's rows. See apps/core/db/rls.py.
        *enable_rls_for("stores_store"),
    ]
