# Generated by Django 5.2.17 on 2026-08-13 21:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_alter_item_options_item_image_item_is_available_and_more'),
        ('payments', '0001_initial'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Generated by the till before any network call. The idempotency key for sync: replaying a batch returns the original sale rather than creating a second one.')),
                ('receipt_number', models.BigIntegerField(blank=True, help_text='Sequential per business, allocated when the sale completes. Gapless, because this is the series tax reporting will read.', null=True)),
                ('receipt_code', models.CharField(blank=True, help_text='The formatted number printed on the receipt.', max_length=40)),
                ('provisional_reference', models.CharField(blank=True, help_text="Printed by a till with no connection, which cannot allocate a business-wide number. Kept after sync so the paper in a customer's hand can still be matched to the fiscal number.", max_length=40)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('REFUNDED', 'Refunded'), ('VOID', 'Void')], db_index=True, default='OPEN', help_text='Derived from the payment and refund ledgers. See sales/states.py.', max_length=20)),
                ('device_sequence', models.BigIntegerField(blank=True, help_text="Monotonic per device, so a gap in a till's own series is visible.", null=True)),
                ('subtotal_cents', models.BigIntegerField(default=0, help_text='Net of tax, after discounts.')),
                ('discount_cents', models.BigIntegerField(default=0, help_text='Line and cart discounts together.')),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField(default=0, help_text='What the customer owes.')),
                ('cart_discount_bps', models.PositiveIntegerField(default=0)),
                ('cart_discount_cents', models.BigIntegerField(default=0)),
                ('rounding_adjustment_cents', models.IntegerField(default=0, help_text='Cash rounds to the shilling because no smaller coin circulates. The difference is recorded so the drawer reconciles exactly rather than drifting a few shillings a day.')),
                ('is_overpaid', models.BooleanField(default=False, help_text='More was taken than was owed, which two successful M-Pesa pushes genuinely can do. Blocks completion until a manager refunds the difference; the money is real and discarding the record would be worse than surfacing it.')),
                ('device_created_at', models.DateTimeField(blank=True, help_text='When the till recorded it. May be well before it reached the server.', null=True)),
                ('server_received_at', models.DateTimeField(blank=True, help_text='When the server first saw it. All reporting uses this: a till with a wrong clock must not move revenue between days.', null=True)),
                ('was_offline', models.BooleanField(default=False, help_text='Rung up with no connection and synced later.')),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
                ('void_reason', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(help_text='Who rang it up. PROTECT, so a sale always keeps a named person.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.device')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_sale',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA_MANUAL', 'M-Pesa, sent separately')], max_length=16)),
                ('amount_cents', models.BigIntegerField()),
                ('reason', models.TextField(help_text='Required. Nothing is given back without an explanation on the record.')),
                ('is_settled', models.BooleanField(default=True, help_text='False while an M-Pesa refund is recorded but not yet sent, so money owed to a customer is visible rather than assumed done.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='Manager or owner. PROTECT, so the authoriser cannot be removed.', on_delete=django.db.models.deletion.PROTECT, related_name='refunds_given', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.sale')),
            ],
            options={
                'db_table': 'sales_refund',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa')], max_length=10)),
                ('amount_cents', models.BigIntegerField(help_text='Applied to the sale.')),
                ('tendered_cents', models.BigIntegerField(default=0, help_text='What was physically handed over, for cash.')),
                ('change_cents', models.BigIntegerField(default=0)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=32)),
                ('mpesa_phone', models.CharField(blank=True, max_length=32)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentintent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Who took it. Null only for a payment applied by an M-Pesa callback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_taken', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
            ],
            options={
                'db_table': 'sales_payment',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleDiscrepancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('TOTALS_MISMATCH', 'Device totals disagree with the server'), ('NEGATIVE_STOCK', 'Sale drove stock below zero'), ('OVERPAID', 'More was taken than was owed'), ('LATE_PAYMENT', 'Payment arrived after the sale was finished')], max_length=20)),
                ('detail', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_discrepancy',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=6)),
                ('unit_price_cents', models.BigIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('line_discount_cents', models.BigIntegerField(default=0)),
                ('cart_discount_share_cents', models.BigIntegerField(default=0, help_text="This line's share of a whole-cart discount, apportioned before tax.")),
                ('tax_rate_bps', models.PositiveIntegerField(default=0)),
                ('tax_is_inclusive', models.BooleanField(default=True)),
                ('net_cents', models.BigIntegerField(help_text='Taxable base after discounts.')),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('gross_cents', models.BigIntegerField(help_text='What this line adds to the total.')),
                ('position', models.PositiveIntegerField(default=0, help_text='Order on the receipt.')),
                ('item', models.ForeignKey(help_text='Kept for reporting. Nothing is read through it at display time.', on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_sale_line',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RefundLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('amount_cents', models.BigIntegerField()),
                ('restock', models.BooleanField(default=True, help_text='Whether the goods go back on the shelf. False for something returned damaged, which is refunded but cannot be sold again.')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.refund')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_lines', to='sales.saleline')),
            ],
            options={
                'db_table': 'sales_refund_line',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'state', '-created_at'], name='sales_sale_tenant__8765cf_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'store', '-created_at'], name='sales_sale_tenant__2e5994_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_uuid'), name='unique_sale_client_uuid_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_number__isnull', False)), fields=('tenant', 'receipt_number'), name='unique_receipt_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='sale_total_not_negative'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant', '-created_at'], name='sales_refun_tenant__88e825_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', '-created_at'], name='sales_payme_tenant__12ca56_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt_number', ''), _negated=True), fields=('tenant', 'mpesa_receipt_number'), name='unique_mpesa_receipt_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='salediscrepancy',
            index=models.Index(fields=['tenant', 'resolved_at', '-created_at'], name='sales_discr_tenant__eeeb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='saleline',
            index=models.Index(fields=['sale', 'position'], name='sales_sale__sale_id_f1e0df_idx'),
        ),
        migrations.AddConstraint(
            model_name='refundline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='refund_line_quantity_positive'),
        ),
        # Tenant isolation is enforced by the database, not only by
        # application code. These tables hold money, so a forgotten filter
        # here would be worse than one anywhere else in the system.
        *enable_rls_for(
            "sales_sale",
            "sales_sale_line",
            "sales_payment",
            "sales_refund",
            "sales_refund_line",
            "sales_discrepancy",
        ),
    ]
