# Generated by Django 5.2.17 on 2026-08-13 21:37

import django.db.models.deletion
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_number', models.BigIntegerField(default=0)),
                ('prefix', models.CharField(default='INV', help_text='Printed before the number, e.g. INV-2026-000001.', max_length=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_receipt_counter',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='one_receipt_counter_per_tenant')],
            },
        ),
        # The counter is per business, so it carries a tenant and needs the
        # same policy as everything else. Without one, a forgotten filter
        # could hand one shop's receipt series to another.
        *enable_rls_for("sales_receipt_counter"),
    ]
