# Generated by Django 5.2.17 on 2026-08-14 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_receiptcounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_authorization_reason',
            field=models.TextField(blank=True, help_text='Required whenever a discount is applied.'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_authorized_label',
            field=models.CharField(blank=True, help_text='Who approved it, captured as text so it survives the account changing.', max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_authorized_via',
            field=models.CharField(blank=True, help_text="SESSION when a manager rang it up themselves, PIN or PASSWORD when a manager approved a cashier's sale at the till, OFFLINE when the device verified it with no connection - which is weaker, and recorded as such rather than quietly equated with the others.", max_length=12),
        ),
    ]
