# Generated by Django 5.2.17 on 2026-08-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_discount_authorization_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed_via',
            field=models.CharField(blank=True, choices=[('CALLBACK', 'Confirmed by callback'), ('RECONCILIATION', 'Confirmed by status query')], help_text='How this payment was confirmed. A payment settled from a status query carries a placeholder reference, because that query does not return an M-Pesa receipt code - so this says whether the reference beside it is a real code or a stand-in.', max_length=16),
        ),
    ]
