# Generated by Django 5.2.17 on 2026-08-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_payment_confirmed_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_authorization_is_stale',
            field=models.BooleanField(default=False, help_text="Set at sync when the version the device checked against no longer matches the manager's current one, meaning the approving PIN was changed or revoked while the till was offline. The sale still lands - the goods left the shop - but it is flagged for a person."),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_authorized_pin_version',
            field=models.PositiveIntegerField(blank=True, help_text="Only for OFFLINE authorisations: which version of the manager's PIN the device's cached copy was, at the moment it checked. Not the hash and nothing derived from the PIN - a counter. Compared against the manager's current version at sync.", null=True),
        ),
        migrations.AlterField(
            model_name='salediscrepancy',
            name='kind',
            field=models.CharField(choices=[('TOTALS_MISMATCH', 'Device totals disagree with the server'), ('NEGATIVE_STOCK', 'Sale drove stock below zero'), ('OVERPAID', 'More was taken than was owed'), ('LATE_PAYMENT', 'Payment arrived after the sale was finished'), ('STALE_AUTH', 'Offline discount approved against a PIN that has since changed'), ('UNKNOWN_DEVICE', 'Sale claimed a till this business does not own')], max_length=20),
        ),
    ]
