# Generated by Django 5.2.17 on 2026-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_discount_authorization_is_stale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='offline_shortfall_cents',
            field=models.BigIntegerField(default=0, help_text='Money this sale should have collected and never will, because the till was pricing from a stale catalogue while it had no connection. Only ever written by sync ingest, never by a live till. Kept separate from the total so that what the sale should have come to and what the shop settled for stay separately visible - folded into the total it would be indistinguishable from a cheaper sale, and the pattern would never be spotted.'),
        ),
        migrations.AlterField(
            model_name='salediscrepancy',
            name='kind',
            field=models.CharField(choices=[('TOTALS_MISMATCH', 'Device totals disagree with the server'), ('NEGATIVE_STOCK', 'Sale drove stock below zero'), ('OVERPAID', 'More was taken than was owed'), ('LATE_PAYMENT', 'Payment arrived after the sale was finished'), ('STALE_AUTH', 'Offline discount approved against a PIN that has since changed'), ('UNKNOWN_DEVICE', 'Sale claimed a till this business does not own'), ('OFFLINE_SHORTFALL', 'Offline till collected less than the sale came to')], max_length=20),
        ),
    ]
