# Generated by Django 5.2.17 on 2026-08-14 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_offline_shortfall_cents_and_more'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Which drawer this money went into. Named explicitly rather than worked out from a time window: a sale rung up during a shift but synced after it closed would fall outside any window and vanish from the reconciliation, which is exactly the sale a shop most needs accounted for. Null for a business that does not run shifts - the feature is optional and a shop that never opens one goes on selling.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shifts.shift'),
        ),
    ]
