# Generated by Django 5.2.17 on 2026-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_payment_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salediscrepancy',
            name='kind',
            field=models.CharField(choices=[('TOTALS_MISMATCH', 'Device totals disagree with the server'), ('NEGATIVE_STOCK', 'Sale drove stock below zero'), ('OVERPAID', 'More was taken than was owed'), ('LATE_PAYMENT', 'Payment arrived after the sale was finished'), ('STALE_AUTH', 'Offline discount approved against a PIN that has since changed'), ('UNKNOWN_DEVICE', 'Sale claimed a till this business does not own'), ('OFFLINE_SHORTFALL', 'Offline till collected less than the sale came to'), ('SUSPICIOUS_QTY', 'A weighed or measured line priced at almost nothing')], max_length=20),
        ),
    ]
