# Generated by Django 5.2.17 on 2026-08-14 21:08

import apps.compliance.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.db.rls import enable_rls_for


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0007_payment_shift'),
        ('tenants', '0002_tenant_compliance_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('INVOICE', 'Tax invoice'), ('CREDIT_NOTE', 'Credit note')], max_length=12)),
                ('invoice_number', models.BigIntegerField(help_text="Gapless per business. Allocated inside the sale's own transaction.")),
                ('invoice_code', models.CharField(help_text='The number as it is printed, e.g. TI-2026-000001.', max_length=40)),
                ('buyer_pin', models.CharField(blank=True, help_text="The customer's tax PIN, when they asked for a tax invoice. Checked for shape only - nothing here can verify it without asking KRA.", max_length=20, validators=[apps.compliance.models.validate_kra_pin])),
                ('seller_pin', models.CharField(blank=True, help_text="The business's own PIN, copied at issue so a later edit cannot rewrite it.", max_length=20)),
                ('net_cents', models.BigIntegerField()),
                ('tax_cents', models.BigIntegerField()),
                ('gross_cents', models.BigIntegerField()),
                ('tax_breakdown', models.JSONField(blank=True, default=list, help_text='Net and tax per rate, as a list of {rate_bps, net_cents, tax_cents}. Snapshotted rather than derived on read, so a rate change next year cannot restate what was declared.')),
                ('issued_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, help_text='Why a credit note was raised. Required on one.')),
                ('adapter', models.CharField(help_text='Which adapter handled it, recorded so a change of regime stays legible.', max_length=32)),
                ('submission_state', models.CharField(choices=[('NOT_REQUIRED', 'Nothing to submit'), ('PENDING', 'Waiting to be sent'), ('SUBMITTED', 'Sent'), ('FAILED', 'Could not be sent')], default='PENDING', max_length=14)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_reference', models.CharField(blank=True, help_text='Whatever the far end called it. Empty for the manual adapter.', max_length=100)),
                ('submission_attempts', models.PositiveIntegerField(default=0)),
                ('failure_detail', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='compliance.compliancedocument')),
                ('sale', models.ForeignKey(help_text='PROTECT: a sale with a tax document against it is not deletable.', on_delete=django.db.models.deletion.PROTECT, related_name='compliance_documents', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'compliance_document',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['tenant', 'submission_state'], name='compliance__tenant__e05a3c_idx'), models.Index(fields=['tenant', '-issued_at'], name='compliance__tenant__97302b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'invoice_number'), name='unique_invoice_number_per_tenant'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'CREDIT_NOTE'), ('original__isnull', False)), models.Q(('kind', 'INVOICE'), ('original__isnull', True)), _connector='OR'), name='credit_note_has_an_original')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_number', models.BigIntegerField(default=0)),
                ('prefix', models.CharField(default='TI', help_text="Printed before the number, e.g. TI-2026-000001. 'Tax invoice'.", max_length=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'compliance_invoice_counter',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='one_invoice_counter_per_tenant')],
            },
        ),
        # Both tables carry a business's tax position. The coverage test walks
        # TenantOwnedModel subclasses and fails the build if either is missing
        # its policy.
        *enable_rls_for("compliance_document", "compliance_invoice_counter"),
    ]
