# Generated by Django 5.2.17 on 2026-08-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='invoice_code',
            field=models.CharField(blank=True, help_text='The number as it is printed, e.g. TI-2026-000001. Empty when unnumbered.', max_length=40),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='invoice_number',
            field=models.BigIntegerField(blank=True, help_text="Gapless per business, allocated inside the sale's own transaction. **Null when nothing will be filed against this document** - a business under no regime, or an offline sale that has not synced. Putting either in the tax series would claim a filing that will never happen. Postgres treats nulls as distinct, so the unique constraint still holds.", null=True),
        ),
    ]
